#!/bin/bash

##cat hicpro2.log | tail -n 32 | grep -v Quality | sed 's/HiC-Pro_2.9.0/HiC-Pro_2.10.0/g' > plot.sh
 
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/H0rep' bwtDir='bowtie_results/bwt2/H0rep' sampleName='H0rep' r1tag='_R1' r2tag='_R2'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_mapping_portion.R logs/H0rep/plot_mapping_portion.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/H0rep' bwtDir='bowtie_results/bwt2/H0rep' sampleName='H0rep' rmMulti='1' rmSingle='1'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_pairing_portion.R logs/H0rep/plot_pairing_portion.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/H24rep' bwtDir='bowtie_results/bwt2/H24rep' sampleName='H24rep' r1tag='_R1' r2tag='_R2'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_mapping_portion.R logs/H24rep/plot_mapping_portion.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/H24rep' bwtDir='bowtie_results/bwt2/H24rep' sampleName='H24rep' rmMulti='1' rmSingle='1'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_pairing_portion.R logs/H24rep/plot_pairing_portion.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/NannoH0' bwtDir='bowtie_results/bwt2/NannoH0' sampleName='NannoH0' r1tag='_R1' r2tag='_R2'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_mapping_portion.R logs/NannoH0/plot_mapping_portion.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/NannoH0' bwtDir='bowtie_results/bwt2/NannoH0' sampleName='NannoH0' rmMulti='1' rmSingle='1'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_pairing_portion.R logs/NannoH0/plot_pairing_portion.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/NannoH24' bwtDir='bowtie_results/bwt2/NannoH24' sampleName='NannoH24' r1tag='_R1' r2tag='_R2'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_mapping_portion.R logs/NannoH24/plot_mapping_portion.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/NannoH24' bwtDir='bowtie_results/bwt2/NannoH24' sampleName='NannoH24' rmMulti='1' rmSingle='1'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_pairing_portion.R logs/NannoH24/plot_pairing_portion.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/H0rep' hicDir='hic_results/data/H0rep' sampleName='H0rep'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_hic_fragment.R logs/H0rep/plot_hic_fragment.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/H0rep' hicDir='hic_results/data/H0rep' sampleName='H0rep'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_hic_contacts.R logs/H0rep/plot_hic_contacts.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/H24rep' hicDir='hic_results/data/H24rep' sampleName='H24rep'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_hic_fragment.R logs/H24rep/plot_hic_fragment.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/H24rep' hicDir='hic_results/data/H24rep' sampleName='H24rep'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_hic_contacts.R logs/H24rep/plot_hic_contacts.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/NannoH0' hicDir='hic_results/data/NannoH0' sampleName='NannoH0'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_hic_fragment.R logs/NannoH0/plot_hic_fragment.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/NannoH0' hicDir='hic_results/data/NannoH0' sampleName='NannoH0'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_hic_contacts.R logs/NannoH0/plot_hic_contacts.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/NannoH24' hicDir='hic_results/data/NannoH24' sampleName='NannoH24'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_hic_fragment.R logs/NannoH24/plot_hic_fragment.Rout
/home/gene/gongyh/.Renv/shims/R --no-save --no-restore CMD BATCH "--args picDir='hic_results/pic/NannoH24' hicDir='hic_results/data/NannoH24' sampleName='NannoH24'" /home/gene/gongyh/bin/HiC-Pro_2.10.0/scripts/plot_hic_contacts.R logs/NannoH24/plot_hic_contacts.Rout
